micronaut:
  application:
    name: ociobjectuploader
oci.config.profile: DEFAULT
netty:
  default:
    allocator:
      max-order: 3
local-upload-dir: /Users/trsharp/Documents/OCI Uploads
oci-namespace: toddrsharp
oci-bucket: screenshots
oci-region: us-phoenix-1
oci-par-duration-hours: 24

