micronaut:
  application:
    name: ociobjectuploader
oci.config.profile: DEFAULT
netty:
  default:
    allocator:
      max-order: 3
uploader:
  local-upload-dir:
  oci:
    namespace:
    bucket:
    region:
    par-duration-hours:

